### ISSUE TITLE
Parse error после переноса сайта на кириллический домен

### ISSUE THREAD

**Issue by olfedos** [SlavaYurthev/Novaposhta#1]
После переноса сайта v1.9.1 на другой хост и домен (кириллический) модуль дает ошибку Parse error: syntax error, unexpected '[' in /var/www/.../app/code/community/SY/Novaposhta/Helper/Data.php on line 21. Подскажите, пожалуйста, в чем может быть причина?

    в лог файле:
    Warning: include(SY/Novaposhta/Model/Observer.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory in /var/www/xn80aabsxh5l/xn--80aabsxh5l.xn--j1amh/lib/Varien/Autoload.php on line 94

    Warning: include() [<a href='function.include'>function.include</a>]: Failed opening 'SY/Novaposhta/Model/Observer.php' for inclusion (include_path='/var/www/xn80aabsxh5l/xn--80aabsxh5l.xn--j1amh/app/code/local:/var/www/xn80aabsxh5l/xn--80aabsxh5l.xn--j1amh/app/code/community:/var/www/xn80aabsxh5l/xn--80aabsxh5l.xn--j1amh/app/code/core:/var/www/xn80aabsxh5l/xn--80aabsxh5l.xn--j1amh/lib:./:/') in /var/www/xn80aabsxh5l/xn--80aabsxh5l.xn--j1amh/lib/Varien/Autoload.php on line 94

**Comment by ghost** [comment]
Проблема явно в пути 
`/var/www/xn80aabsxh5l/xn--80aabsxh5l.xn--j1amh/lib/Varien/`

Unix скорее всего не может определить что это за кракозябры в пути к файлу

Настройте на сервере нормальный путь к файлам, латиницей

**Comment by olfedos** [comment]
Да, согласна, но домен кириллический и url сайта прописан именно так - паникодом.

**Comment by olfedos** [comment]
Да, согласна, но домен кириллический и url сайта прописан именно так - паникодом.
